name: Build & Release Dolby Unified Player APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Signed Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        run: |
          sudo apt-get update -q
          sudo apt-get install -y wget unzip
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip -q cmdtools.zip -d $HOME/android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/ || true
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Install npm dependencies
        run: npm ci

      - name: Capacitor sync
        run: npx cap sync android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Decode release keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/dolby-release.jks

      - name: Build signed release APK
        working-directory: android
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=${{ github.workspace }}/android/app/dolby-release.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Rename APK
        run: |
          mv android/app/build/outputs/apk/release/app-release.apk \
             android/app/build/outputs/apk/release/DolbyUnifiedPlayer.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: DolbyUnifiedPlayer-APK
          path: android/app/build/outputs/apk/release/DolbyUnifiedPlayer.apk
          retention-days: 30

      - name: Create Codeberg Release
        run: |
          TAG="v1.0.0-build${{ github.run_number }}"
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
            -H "Content-Type: application/json" \
            "https://codeberg.org/api/v1/repos/${{ github.repository }}/releases" \
            -d "{
              \"tag_name\": \"$TAG\",
              \"name\": \"Dolby Unified Player Build ${{ github.run_number }}\",
              \"body\": \"Automated release — APK attached as download.\",
              \"draft\": false,
              \"prerelease\": false
            }" > release.json
          RELEASE_ID=$(cat release.json | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.FORGEJO_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            "https://codeberg.org/api/v1/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=DolbyUnifiedPlayer.apk" \
            --data-binary @android/app/build/outputs/apk/release/DolbyUnifiedPlayer.apk